/* =====================================================
   PAYMENT.JS — SECURE KEY VERIFICATION
   Keys are validated AGAINST FIREBASE first,
   then fallback to hardcoded legacy keys.
   Unlocks the correct subject in the user's Firestore
   doc so the trial system respects it.
===================================================== */

import { initializeApp }         from "https://www.gstatic.com/firebasejs/12.11.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.11.0/firebase-auth.js";
import {
    getFirestore,
    doc, getDoc, updateDoc, setDoc,
    collection, query, where, getDocs,
    serverTimestamp
} from "https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js";

// ─── Firebase ───────────────────────────────────────────────────────────────
const firebaseConfig = {
    apiKey:            "AIzaSyCd7l9eOMbO7F4TSuV55VqnaJUQbFvsibA",
    authDomain:        "codex-study-hub-923c5.firebaseapp.com",
    projectId:         "codex-study-hub-923c5",
    storageBucket:     "codex-study-hub-923c5.appspot.com",
    messagingSenderId: "750631534625",
    appId:             "1:750631534625:web:5f59e1841bb856bdbba360"
};

const app  = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db   = getFirestore(app);

// ─── Config ──────────────────────────────────────────────────────────────────
const WHATSAPP_NUMBER = "2347011245168";
const PRICE           = "₦300";

/* ─────────────────────────────────────────────────────────────────────────────
   LEGACY HARDCODED KEYS (backward compatibility)
   These are the old-format keys (CX-XXXX-X) that were pre-generated.
   New keys are generated by admin_keys.html and stored in Firebase.
───────────────────────────────────────────────────────────────────────────── */
const LEGACY_KEYS = [
    "CX-4927-Q","CX-8103-M","CX-2759-Z","CX-6381-A","CX-9402-K",
    "CX-1876-R","CX-5590-B","CX-7024-Y","CX-3669-P","CX-8241-W",
    "CX-5937-H","CX-1048-X","CX-9472-N","CX-6805-C","CX-2519-T",
    "CX-7386-J","CX-4097-F","CX-8921-D","CX-5604-L","CX-9738-E",
    "CX-6148-V","CX-2957-S","CX-8401-G","CX-1769-U","CX-5328-M",
    "CX-9604-Q","CX-3475-B","CX-7812-Z","CX-4590-A","CX-6087-K",
    "CX-1946-R","CX-8359-Y","CX-2704-P","CX-9168-W","CX-5421-H",
    "CX-7093-X","CX-3865-N","CX-8249-C","CX-1570-T","CX-6914-J",
    "CX-4386-F","CX-9207-D","CX-5649-L","CX-1783-E","CX-7035-V",
    "CX-8492-S","CX-2157-G","CX-9061-U","CX-4328-M","CX-6709-Q",
    "CX-3984-B","CX-7541-Z","CX-2806-A","CX-9153-K","CX-6472-R",
    "CX-5019-Y","CX-8634-P","CX-2948-W","CX-7106-H","CX-4827-X",
    "CX-9360-N","CX-1584-C","CX-6942-T","CX-3075-J","CX-8219-F"
];

let currentUser    = null;
let selectedSubject = null;

// Track auth
onAuthStateChanged(auth, (user) => {
    currentUser = user;
    if (user) {
        console.log("Authenticated:", user.email);
    }
});

// ─── Subject selection ────────────────────────────────────────────────────────
window.onSubjectChange = function() {
    const subject  = document.getElementById("subjectSelect").value;
    const priceDiv = document.getElementById("priceDisplay");
    const subjName = document.getElementById("subjName");

    selectedSubject = subject;

    if (subject) {
        priceDiv.style.display = "flex";
        subjName.textContent   = subject;
    } else {
        priceDiv.style.display = "none";
    }
};

// ─── WhatsApp ─────────────────────────────────────────────────────────────────
window.openWhatsApp = function() {
    const subject = document.getElementById("subjectSelect").value;
    if (!subject) { showError("⚠️ Please select a subject first."); return; }

    const userInfo = currentUser ? `\nAccount: ${currentUser.email}` : "";
    const msg = encodeURIComponent(
        `Hi! I want to unlock ${subject} for ${PRICE}.${userInfo}\nPlease send me a verification key.`
    );
    window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`, '_blank');
};

// ─── Bank modal ───────────────────────────────────────────────────────────────
window.showBankDetails = function() {
    const subject = document.getElementById("subjectSelect").value;
    if (!subject) { showError("⚠️ Please select a subject first."); return; }
    document.getElementById("bankModal").classList.add("open");
};

window.closeBankModal = function() {
    document.getElementById("bankModal").classList.remove("open");
};

// ─── VERIFY KEY — main fix ────────────────────────────────────────────────────
window.verifyKey = async function() {
    const subject = document.getElementById("subjectSelect").value;
    const keyRaw  = document.getElementById("keyInput").value.trim().toUpperCase();

    hideMessages();

    // — validation —
    if (!subject)  { showError("⚠️ Please select a subject first."); return; }
    if (!keyRaw)   { showError("⚠️ Please enter a verification key."); return; }
    if (!currentUser) {
        showError("⚠️ You must be logged in to verify a key. Please log in first.");
        return;
    }

    // — loading state —
    const btn = document.getElementById("verifyBtn");
    const originalHTML = btn.innerHTML;
    btn.innerHTML  = '<span class="spinner"></span> Verifying...';
    btn.disabled   = true;

    try {
        // ══════════════════════════════════════════════════════
        // STEP 1: Check Firebase "valid_keys" collection FIRST
        //         (These are keys generated by admin_keys.html)
        // ══════════════════════════════════════════════════════
        const keyDocRef  = doc(db, "valid_keys", keyRaw);
        const keyDocSnap = await getDoc(keyDocRef);

        let keyIsValid   = false;
        let keySubject   = subject;   // default to what user selected
        let isFirebaseKey = false;

        if (keyDocSnap.exists()) {
            const keyData = keyDocSnap.data();

            // Check if this Firebase key was already used
            if (keyData.used === true) {
                showError("❌ This key has already been used.");
                btn.innerHTML = originalHTML;
                btn.disabled  = false;
                return;
            }

            // Firebase keys embed the subject — use that (more secure)
            keySubject   = keyData.subject || subject;
            keyIsValid   = true;
            isFirebaseKey = true;

            // Verify the selected subject matches key's subject
            if (keyData.subject && keyData.subject !== subject) {
                showError(
                    `❌ This key is for ${keyData.subject}, not ${subject}. ` +
                    `Please select ${keyData.subject} from the dropdown.`
                );
                btn.innerHTML = originalHTML;
                btn.disabled  = false;
                return;
            }

        } else {
            // ════════════════════════════════════════════════════
            // STEP 2: Fallback — check legacy hardcoded key list
            // ════════════════════════════════════════════════════
            if (LEGACY_KEYS.includes(keyRaw)) {
                keyIsValid = true;
                isFirebaseKey = false;
            }
        }

        if (!keyIsValid) {
            showError("❌ Invalid verification key. Please check and try again.");
            btn.innerHTML = originalHTML;
            btn.disabled  = false;
            return;
        }

        // ════════════════════════════════════════════════════════
        // STEP 3: Check if user already used this key (Firestore)
        // ════════════════════════════════════════════════════════
        const userRef  = doc(db, "users", currentUser.uid);
        const userSnap = await getDoc(userRef);
        const userData = userSnap.exists() ? userSnap.data() : {};

        const usedKeys = userData.used_keys || [];
        if (usedKeys.includes(keyRaw)) {
            showError("❌ You have already used this key.");
            btn.innerHTML = originalHTML;
            btn.disabled  = false;
            return;
        }

        // ════════════════════════════════════════════════════════
        // STEP 4: Unlock the subject in user's Firestore doc
        //  - unlocked_SUBJECT = true  (used by subject_selection.html)
        // ════════════════════════════════════════════════════════
        const unlockPayload = {
            [`unlocked_${keySubject}`]:   true,
            [`unlockedAt_${keySubject}`]: serverTimestamp(),
            used_keys: [...usedKeys, keyRaw],
            lastUpdated: serverTimestamp()
        };

        if (userSnap.exists()) {
            await updateDoc(userRef, unlockPayload);
        } else {
            await setDoc(userRef, {
                email: currentUser.email,
                createdAt: serverTimestamp(),
                ...unlockPayload
            });
        }

        // ════════════════════════════════════════════════════════
        // STEP 5: Mark Firebase key as USED (prevents reuse)
        // ════════════════════════════════════════════════════════
        if (isFirebaseKey) {
            await updateDoc(keyDocRef, {
                used:       true,
                usedBy:     currentUser.email,
                usedAt:     serverTimestamp()
            });
        }

        // ════════════════════════════════════════════════════════
        // STEP 6: Also update localStorage for instant UI update
        // ════════════════════════════════════════════════════════
        try {
            const sess = JSON.parse(localStorage.getItem('loggedInUser') || '{}');
            sess[`unlocked_${keySubject}`] = true;
            localStorage.setItem('loggedInUser', JSON.stringify(sess));
        } catch(e) {}

        // — success —
        showSuccess(`✅ ${keySubject} unlocked successfully! Redirecting to home...`);
        document.getElementById("keyInput").value = "";

        setTimeout(() => { window.location.href = "home.html"; }, 2200);

    } catch (error) {
        console.error("Unlock error:", error);
        showError("❌ Error verifying key: " + error.message);
    } finally {
        btn.innerHTML = originalHTML;
        btn.disabled  = false;
    }
};

// ─── UI helpers ───────────────────────────────────────────────────────────────
function showError(msg) {
    document.getElementById("errorMsg").textContent   = msg;
    document.getElementById("errorMsg").style.display = "block";
    document.getElementById("successMsg").style.display = "none";
}

function showSuccess(msg) {
    document.getElementById("successMsg").textContent   = msg;
    document.getElementById("successMsg").style.display = "block";
    document.getElementById("errorMsg").style.display   = "none";
}

function hideMessages() {
    document.getElementById("errorMsg").style.display   = "none";
    document.getElementById("successMsg").style.display = "none";
}

window.goBack = function() { window.history.back(); };
